version: '3.9'
services:
  podcast_db:
    image: postgres:15.3-alpine
    container_name: podcast_db
    ports:
      - 5432:5432
    volumes:
      - podcast_postgres_data:/usr/share/podcast_postgres/data
    env_file:
      - ./database/.env.local.db

  podcast_pgadmin:
    image: podcast_pgadmin4
    build:
      context: dockerfiles/pgadmin4
      dockerfile: ./pgadmin.dockerfile
    container_name: pgadmin4_container
    ports:
      - 5050:80
    env_file:
      - ./database/.env.local.db
    depends_on:
      - podcast_db

  mongo:
    image: mongo
    restart: always
    container_name: podcast_mongo
    ports:
      - 27017:27017
    env_file:
      - ./database/.env.local.db
    volumes:
      - podcast_mongo_data:/usr/share/podcast_mongo/data

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    env_file:
      - ./database/.env.local.db
    depends_on:
      - mongo

volumes:
  podcast_postgres_data:
  podcast_mongo_data:
